### ISSUE TITLE
New settings for Augmented Teacher for sending notifications

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-local_augmented_teacher#7]
@superfoght commented on [Mon May 30 2022](https://github.com/praxisdigital/moodle-opgaver/issues/95)

As it is now, the reminders to login, are sent continuously. If you have set the reminder to be sent after X days, it sends the reminder again X days after the first reminder. 

**The below should be implemented by some sort of setting, if possible**

**_Please let me know before implementing if either scenario is possible/not possible_**

### Current scenario
- You set the reminder to login to send a notification after 5 days
- After 5 days it sends a notification
- After another 5 days without login it sends another notification
- And this continues until the user logs in.

### The scenario the client wants
- You set the reminder to login to send a notification after 5 days
- After 5 days it sends a notification
- After another 5 days without login it doesn't send another notification
- The user then logs in and will never recieve notifications to log in again, even if they fail to log in for five days.

**_If the above scenario is not possible please let me know, so I can inform the client._**

### Alternative scenario (if the above is not possible and the client okays this)
- You set the reminder to login to send a notification after 5 days
- After 5 days it sends a notification
- After another 5 days without login it doesn't send another notification
- No further notifications are sent out, before the user logs in again.
- After the user has logged in, another 5 days go by without a login and then another notification is sent out. 

Zendesk: https://praxisdigital.zendesk.com/agent/tickets/39034

**Comment by frederikmillingpytlick** [comment]
Hi @superfoght,

I've created a new branch on our fork: [fmp_GH-7_311](https://github.com/praxisdigital/moodle-local_augmented_teacher/tree/fmp_GH-7_311) with the functionality. 

I've added a setting: "resend_notloggedin_notification_infinitely", which toggles whether the notification should be sent more than once

Could you have a look at it when you have some spare time? :smile:

PR:
https://github.com/praxisdigital/moodle-local_augmented_teacher/pull/8

After merge contact me or someone from the moodle team, so they can merge it into the [forked repository](https://github.com/smartlearningdk/moodle-local_augmented_teacher).

**Comment by superfoght** [comment]
@mcardle I have tested that this works. 
Can you or someone else look into the last part @frederikmillingpytlick wrote: 

"After merge contact me or someone from the moodle team, so they can merge it into the [forked repository](https://github.com/smartlearningdk/moodle-local_augmented_teacher)."

**Comment by frederikmillingpytlick** [comment]
@Mikkeljeppesen1 could you update local_augmented_teacher to the latest version on all sites? 

Version: 2022073000

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick do we need to get the clients wich have the original local_augmented_teacher to use the forked version?

**Comment by frederikmillingpytlick** [comment]
@Mikkeljeppesen1 They should be in sync, but we would prefer if all sites used our fork, so that we have full control over updates coming in
